name: Test and build Android apk
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '13.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi